ALTER TABLE orders
ADD COLUMN vat_enabled_at_sale TINYINT(1) NOT NULL DEFAULT 0,
ADD COLUMN vat_rate_at_sale DECIMAL(5,2) NOT NULL DEFAULT 0.00,
ADD COLUMN vat_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
ADD COLUMN subtotal DECIMAL(10,2) NOT NULL DEFAULT 0.00;